apiVersion: v2
name: hello-world-app
description: A Helm chart for Hello World Flask application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - flask
  - kubernetes
  - hello-world
maintainers:
  - name: DevOps Team
home: https://github.com/your-org/your-repo
sources:
  - https://github.com/your-org/your-repo
