apiVersion: v2
name: hello-world-app
description: A production-ready Hello World application with PostgreSQL
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - hello-world
  - flask
  - postgresql
maintainers:
  - name: DevOps Team
    email: devops@example.com
dependencies:
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled