{{- if not .Values.database.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-world-app.fullname" . }}-db
  labels:
    {{- include "hello-world-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  username: {{ "appuser" | b64enc | quote }}
  password: {{ "changeme" | b64enc | quote }}
  {{- end }}
{{- end }}